# ルール一覧
# https://realm.github.io/SwiftLint/rule-directory.html

disabled_rules:
  - opening_brace
  - line_length
  - trailing_whitespace
  - force_cast
  - force_try

included:
  - iOSEngineerCodeCheck

cyclomatic_complexity:
  warning: 30

function_body_length:
  warning: 100

large_tuple:
  warning: 3

identifier_name:
  min_length:
    warning: 1
    error: 1

nesting:
  type_level:
    warning: 2
    error: 4

type_name:
  max_length: 50
